### ISSUE TITLE
Naming convention for .conf-file

### ISSUE THREAD

**Issue by Grub4K** [CogentRedTester/mpv-sub-select#1]
Naming the configuration file `sub_select.conf` breaks with the other two filenames and is confusing at first.
I would suggest changing it to `opt.read_options(o, "sub-select")` in the main script to keep the naming consistent or change the two other files to `sub_select` too.

**Comment by CogentRedTester** [comment]
Calling it sub_select is to conform to the standard naming conventions of other mpv scripts. The default name for the config file of a script is the filename with characters like hyphens substututed for  `_`.

I also don't want to change the script name to use underlines because it would break the naming conventions of my other scripts.

Perhaps the Json file should have used underlines as well, but now that I'm using similar naming schemes for the json files in my other scripts, I also don't really want you chance it.

Unless you can justify making a breaking change for several scripts I'll be leaving things as they are.
